remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: NYU DevOps Troubleshooting Guide
description: A guide to troubleshooting common issues in the NYU DevOps class
markdown: kramdown
kramdown:
  input: GFM

author: NYU Devops TA - Dhruv Shetty

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Home: README.md